name: Pull request

on:
  pull_request: 
    branches: [ main ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Check changes
        run: pnpm run check