name: Sync Data

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Fetch and update data
        run: |
          echo "Fetching data from external source..."
          # This workflow fetches data from external APIs
          # and updates the JSON files in public/data/
          # Example: curl -o public/data/characters.json https://api.example.com/characters
          # Example: curl -o public/data/account.json https://api.example.com/account
          echo "Data fetch complete"
      
      - name: Copy JSON files to public directory
        run: |
          echo "Ensuring data files are in public/data/"
          mkdir -p public/data
          # If fetching from a temporary location, copy files here
          # Example: cp tmp/characters.json public/data/
          # Example: cp tmp/account.json public/data/
          ls -la public/data/
      
      - name: Commit and push if changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/data/*.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: sync data [skip ci]" && git push)
